"""initial_tables

Revision ID: 035d4db170cd
Revises: 
Create Date: 2026-03-08 07:20:03.102975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '035d4db170cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azure_oid', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('phone_office', sa.String(length=20), nullable=True),
    sa.Column('phone_mobile', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('interests', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('allowed_ips', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_oid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('replied_by', sa.Integer(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['replied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('collateral_large', sa.String(length=20), nullable=True),
    sa.Column('collateral_small', sa.String(length=50), nullable=True),
    sa.Column('cutoff_date', sa.Date(), nullable=True),
    sa.Column('bid_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('sale_method', sa.String(length=50), nullable=True),
    sa.Column('bidder_count', sa.Integer(), nullable=True),
    sa.Column('debtor_type', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('debtor_count', sa.Integer(), nullable=True),
    sa.Column('bond_count', sa.Integer(), nullable=True),
    sa.Column('avg_overdue_months', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('opb', sa.BigInteger(), nullable=True),
    sa.Column('sale_price', sa.BigInteger(), nullable=True),
    sa.Column('sale_ratio', sa.Numeric(precision=7, scale=4), sa.Computed('CASE WHEN opb > 0 THEN sale_price::NUMERIC / opb ELSE NULL END', persisted=True), nullable=True),
    sa.Column('resale_included', sa.Boolean(), nullable=True),
    sa.Column('resale_debtor_count', sa.Integer(), nullable=True),
    sa.Column('resale_bond_count', sa.Integer(), nullable=True),
    sa.Column('resale_opb', sa.BigInteger(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path_enc', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_path_enc', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('advisor', sa.String(length=200), nullable=True),
    sa.Column('buyer_checklist_ok', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool_participants',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('participated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], ),
    sa.PrimaryKeyConstraint('pool_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pool_participants')
    op.drop_table('pool_companies')
    op.drop_table('notices')
    op.drop_table('documents')
    op.drop_table('pools')
    op.drop_table('consultings')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('glossary')
    op.drop_table('companies')
    # ### end Alembic commands ###
